#!/usr/bin/env python3
"""Replace front-matter placeholders in the journal-style DOCX draft.

The script intentionally handles only the placeholders generated by
``md_to_docx_with_images.py --journal-style``. It does not rewrite body text.
"""

from __future__ import annotations

import json
import sys
import zipfile
from pathlib import Path

from validate_submission_info import validate_info


PLACEHOLDER_MAP = {
    "作者：待作者补充": "作者：{authors_cn}",
    "作者单位：待作者补充二级单位、城市和邮编": "作者单位：{affiliations_cn}",
    "Authors: To be completed": "Authors: {authors_en}",
    "Affiliations: To be completed": "Affiliations: {affiliations_en}",
    "中图分类号：待作者确认    文献标识码：A    文章编号：编辑部填写": (
        "中图分类号：{clc}    文献标识码：{document_code}    文章编号：{article_id}"
    ),
    "基金项目：待作者补充    作者简介/通信作者：待作者补充": (
        "基金项目：{funding}    作者简介：{author_bio}    通信作者：{corresponding_author}"
    ),
    "基金项目：待作者补充": "基金项目：{funding}",
    "作者简介/通信作者：待作者补充": (
        "作者简介：{author_bio}    通信作者：{corresponding_author}"
    ),
}


REQUIRED_KEYS = {
    "authors_cn",
    "authors_en",
    "affiliations_cn",
    "affiliations_en",
    "clc",
    "document_code",
    "article_id",
    "funding",
    "author_bio",
    "corresponding_author",
}


def load_info(path: Path) -> dict[str, str]:
    success, report = validate_info(path, allow_placeholders=False)
    if not success:
        raise SystemExit(report)
    data = json.loads(path.read_text(encoding="utf-8"))
    missing = sorted(REQUIRED_KEYS - set(data))
    if missing:
        raise SystemExit(f"Missing keys in {path}: {', '.join(missing)}")
    return {key: str(value) for key, value in data.items()}


def fill_docx(template: Path, info_path: Path, output: Path) -> None:
    info = load_info(info_path)
    with zipfile.ZipFile(template, "r") as zin, zipfile.ZipFile(
        output, "w", compression=zipfile.ZIP_DEFLATED
    ) as zout:
        for item in zin.infolist():
            data = zin.read(item.filename)
            if item.filename == "word/document.xml":
                text = data.decode("utf-8")
                for old, new_template in PLACEHOLDER_MAP.items():
                    text = text.replace(old, new_template.format(**info))
                data = text.encode("utf-8")
            zout.writestr(item, data)


def main() -> int:
    if len(sys.argv) != 4:
        print(
            "Usage: fill_docx_front_matter.py template.docx info.json output.docx",
            file=sys.stderr,
        )
        return 2
    fill_docx(Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
